title: Chrome parameters
description: A chrome extension that show parameters in a URL
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions

github:
  zip_url: https://github.com/dreamos82/chrome_parameters/archive/refs/tags/1.6.1.zip
  tar_url: https://github.com/dreamos82/chrome_parameters/archive/refs/tags/1.6.1.tar.gz
